### ISSUE TITLE
Not all classes that are returned by icons.getClass exist in style.css

### ISSUE THREAD

**Issue by capfel** [websemantics/file-icons-js#1]
Steps to reproduce:

1. var iconClass = icons.getClass("test.pdf");
2. iconClass is now "icon-file-pdf"
3. This class is not defined in style.css so no icon is shown

The same applies for icon-file-text, I didn't check if there are more cases.

Would be great if this could be fixed as those are pretty standard file types.

**Comment by websemantics** [comment]
I'll surely have a look, thanks for the feedback

**Comment by websemantics** [comment]
Should be fixed now,

**Comment by capfel** [comment]
Thanks!
Can you create a release from that fix so I can update to it in my package.json?

**Comment by websemantics** [comment]
Thanks for heads-up, .. should work now
