### ISSUE TITLE
Swift icon color should be orange

### ISSUE THREAD

**Issue by colinhumber** [websemantics/file-icons-js#4]
The current Swift icon color is set to `medium-green`. However, the official Swift icon is a shade of orange, looks to be `#DF5C43` or thereabouts. The official Swift logo can be found [here](https://swift.org/).

![screen shot 2018-03-09 at 10 30 12 am](https://user-images.githubusercontent.com/104855/37220777-e3448dd6-2384-11e8-8614-5cb2c373bf79.png)

**Comment by websemantics** [comment]
Updated the colour, thank you.
